"""empty message

Revision ID: 5d194b7f8c35
Revises: 67b478221d58
Create Date: 2022-08-11 10:01:56.264964

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5d194b7f8c35'
down_revision = '67b478221d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('planet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('firstName', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('lastName', sa.String(length=30), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('user', 'lastName')
    op.drop_column('user', 'firstName')
    op.drop_table('planet')
    # ### end Alembic commands ###
