"""empty message

Revision ID: 9ad1a83de585
Revises: c7888a1f5f49
Create Date: 2022-08-11 10:07:16.478858

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9ad1a83de585'
down_revision = 'c7888a1f5f49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peopleFavourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'person_id')
    )
    op.create_table('planetFavourites',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'planet_id')
    )
    op.add_column('planet', sa.Column('rotation_period', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('orbital_period', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('diameter', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('climate', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('gravity', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('terrain', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('surface_water', sa.String(length=100), nullable=False))
    op.add_column('planet', sa.Column('population', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'planet', ['terrain'])
    op.create_unique_constraint(None, 'planet', ['rotation_period'])
    op.create_unique_constraint(None, 'planet', ['surface_water'])
    op.create_unique_constraint(None, 'planet', ['orbital_period'])
    op.create_unique_constraint(None, 'planet', ['population'])
    op.create_unique_constraint(None, 'planet', ['diameter'])
    op.create_unique_constraint(None, 'planet', ['climate'])
    op.create_unique_constraint(None, 'planet', ['gravity'])
    op.drop_column('planet', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('url', mysql.VARCHAR(length=80), nullable=False))
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_constraint(None, 'planet', type_='unique')
    op.drop_column('planet', 'population')
    op.drop_column('planet', 'surface_water')
    op.drop_column('planet', 'terrain')
    op.drop_column('planet', 'gravity')
    op.drop_column('planet', 'climate')
    op.drop_column('planet', 'diameter')
    op.drop_column('planet', 'orbital_period')
    op.drop_column('planet', 'rotation_period')
    op.drop_table('planetFavourites')
    op.drop_table('peopleFavourites')
    # ### end Alembic commands ###
